### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by whdgnszz1** [JHeeKimm/PivvyLilt#21]
작성해주신 코드 잘 확인했습니다.

# 1. Next.js를 Next답게 잘 사용하고 있는지 확인 받고 싶습니다..
- Next프로젝트를 한다고 해서 꼭 Next기능을 전부 사용해야 한다는 생각은 안하셨으면 좋겠습니다. 특히 앱 라우팅의 경우 Next 프레임워크에 의존하게 되고, 오류가 자주 발생하여 잘 사용하지 않는 기능입니다. React와 Next의 차이점에 대해 잘 생각해보시고, 어느 부분을 가져가야 하는지 다시 한 번 생각해보시길 바랍니다. 이 부분에 대한 답변은 멘토링때 전달드리도록 하겠습니다.
 
# 2. use client, use server가 적절하게 들어가있는지 알고 싶습니다.
- use server가 적용된 컴포넌트는 회원가입, 로그인 로직 등으로 보입니다.
-  회원가입 시에는 비밀번호와 같은 민감한 정보가 포함되어 있으므로, 클라이언트가 직접 접근하지 못하도록 서버에서 안전하게 처리하는 것이 중요합니다. "use server" 방식을 사용하면 클라이언트가 함수에 직접 접근할 수 없기 때문에 회원가입 로직이 안전하게 보호됩니다. 또, 회원가입에는 종종 이메일 검증, 데이터베이스 초기 설정 등이 포함되며, 이를 서버에서 바로 처리하는 것이 효율적입니다. 마지막으로 회원가입은 한 번만 수행되는 작업으로, 네트워크 비용을 줄이기 위해 클라이언트에서 Route Handler로 요청을 보내는 대신, 서버 측에서 한 번에 모든 로직을 처리하는 것이 더 빠르고 효율적입니다.

- 로그인 후에는 클라이언트에서 사용자 정보를 관리해야 하는 경우가 많습니다. TanStack Query의 Mutation을 사용하면 클라이언트 측에서 로그인 상태를 자동으로 관리하고 캐싱할 수 있어, 다른 컴포넌트에서도 로그인 상태나 사용자 정보를 쉽게 공유할 수 있습니다. 로그인 API는 앱의 여러 컴포넌트나 페이지에서 호출될 가능성이 높으므로, Route Handler를 통한 API 엔드포인트로 만들어 재사용하기 쉽게 설계하는 것이 좋습니다. TanStack Query는 클라이언트에서 상태를 지속적으로 업데이트하고 유지하기 좋으므로, 로그인 상태 관리나 자동 로그인 갱신에도 유리합니다. 로그인 실패 시 클라이언트에서 바로 에러 메시지를 처리하고 사용자에게 피드백을 제공하는 것이 중요합니다. TanStack Query는 에러 핸들링을 쉽게 해주며, 클라이언트 상태 관리를 통한 유저 피드백 제공이 편리해집니다.

- 회원가입은 "use server" 방식이 보안성, 성능 면에서 더 적합합니다.
- 로그인은 클라이언트 상태 관리와 API 재사용성을 고려하여 TanStack Query와 Route Handler를 사용하는 것이 효율적입니다.

# 3. route handlers 부분의 코드와 tanstack-query에서 호출하는 코드가 각 목적에 맞게 코드가 들어가 있는지가 궁금합니다.
- 작성해주신 post와 comment에 대한 TanStack Query와 Route Handler 코드는 적절하게 설정된 것으로 보입니다.
TanStack Query와 Route Handler는 각기 다른 목적을 위해 사용되며, 그 역할이 잘 분리되어 있습니다. TanStack Query는 클라이언트 측에서 요청을 보내고, 받은 데이터를 캐싱하여 다른 컴포넌트에서 쉽게 접근할 수 있도록 돕습니다. 이를 통해 클라이언트는 데이터 요청과 캐싱을 쉽게 관리하고, 불필요한 서버 요청을 줄이며 상태 동기화를 유지할 수 있습니다.
Route Handler는 서버 측에서 로직을 수행하는 부분을 담당하며, TanStack Query가 요청한 작업을 서버에서 처리합니다. 이는 데이터베이스 CRUD 작업이나 비즈니스 로직을 안전하게 서버에서 실행할 수 있도록 하며, 클라이언트가 요청을 보내면 이를 대신 수행하여 결과를 반환하는 역할을 합니다.
따라서, 현재 구성된 코드에서는 TanStack Query가 클라이언트의 요청과 캐싱을 담당하고, Route Handler가 서버의 로직을 수행하는 점이 잘 반영되어 있어 목적에 맞게 구현된 것으로 보입니다.

**Comment by JHeeKimm** [comment]
피드백 감사합니다!
